# -*- coding: utf-8 -*-
"""Untitled7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11yB-tMfPDbm4--GM-lXVm0FPnSsm5DSI
"""

import torch
from transformers import GPT2LMHeadModel,GPT2Tokenizer
model=GPT2LMHeadModel.from_pretrained('gpt2')
tokenizer=GPT2Tokenizer.from_pretrained('gpt2')
def generate_text(prompt,max_length=100):
  input_ids = tokenizer.encode(prompt, return_tensors='pt')
  output=model.generate(input_ids,max_length=max_length)
  generated_text=tokenizer.decode(output[0],skip_special_tokens=True)
  return generated_text
prompt="write a paragraph about artificial intelligence."
generated_text=generate_text(prompt)
print(generated_text)